.TH "Содержание директории C:/Users/yana/Desktop/tmp/Essakov/memory_trainer_game/MemoryTrainer/Memory Trainer/Properties" 3 "Вс 8 Дек 2019" "Тренажер памяти" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории C:/Users/yana/Desktop/tmp/Essakov/memory_trainer_game/MemoryTrainer/Memory Trainer/Properties
.SH SYNOPSIS
.br
.PP
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBAssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "файл \fBResources\&.Designer\&.cs\fP"
.br
.ti -1c
.RI "файл \fBSettings\&.Designer\&.cs\fP"
.br
.in -1c
