.TH "Содержание директории C:/Users/yana/Desktop/tmp/Essakov/memory_trainer_game/MemoryTrainer/Memory Trainer/obj/Debug" 3 "Вс 8 Дек 2019" "Тренажер памяти" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории C:/Users/yana/Desktop/tmp/Essakov/memory_trainer_game/MemoryTrainer/Memory Trainer/obj/Debug
.SH SYNOPSIS
.br
.PP
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBTemporaryGeneratedFile_036C0B5B\-1481\-4323\-8D20\-8F5ADCB23D92\&.cs\fP"
.br
.ti -1c
.RI "файл \fBTemporaryGeneratedFile_5937a670\-0e60\-4077\-877b\-f7221da3dda1\&.cs\fP"
.br
.ti -1c
.RI "файл \fBTemporaryGeneratedFile_E7A71F73\-0F8D\-4B9B\-B56E\-8E70B10BC5D3\&.cs\fP"
.br
.in -1c
