.TH "Содержание директории C:/Users/yana/Desktop/tmp/Essakov" 3 "Вс 8 Дек 2019" "Тренажер памяти" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории C:/Users/yana/Desktop/tmp/Essakov
.SH SYNOPSIS
.br
.PP
.SS "Директории"

.in +1c
.ti -1c
.RI "директория \fBmemory_trainer_game\fP"
.br
.in -1c
