.TH "C:/Users/yana/Desktop/tmp/Essakov/memory_trainer_game/MemoryTrainer/Memory Trainer/FormMemoryTrainer.Designer.cs" 3 "Вс 8 Дек 2019" "Тренажер памяти" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/yana/Desktop/tmp/Essakov/memory_trainer_game/MemoryTrainer/Memory Trainer/FormMemoryTrainer.Designer.cs
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBMemory_Trainer\&.FormMemoryTrainer\fP"
.br
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBMemory_Trainer\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Тренажер памяти из исходного текста\&.
