.TH "G:/desktop_backup/memory_trainer_game/MemoryTrainer/Memory Trainer/FormAboutThimbles.cs" 3 "Вс 8 Дек 2019" "Тренажер памяти" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/desktop_backup/memory_trainer_game/MemoryTrainer/Memory Trainer/FormAboutThimbles.cs
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBMemory_Trainer\&.FormAboutThimbles\fP"
.br
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBMemory_Trainer\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Тренажер памяти из исходного текста\&.
