.TH "Содержание директории G:/desktop_backup/memory_trainer_game" 3 "Вс 8 Дек 2019" "Тренажер памяти" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории G:/desktop_backup/memory_trainer_game
.SH SYNOPSIS
.br
.PP
.SS "Директории"

.in +1c
.ti -1c
.RI "директория \fBMemoryTrainer\fP"
.br
.in -1c
