.TH "Memory_Trainer.IGameInterface" 3 "Вс 8 Дек 2019" "Тренажер памяти" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Memory_Trainer.IGameInterface
.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "void \fBSaveGame\fP ()"
.br
.ti -1c
.RI "void \fBOpenGame\fP ()"
.br
.ti -1c
.RI "void \fBShowRules\fP ()"
.br
.ti -1c
.RI "void \fBShowInfo\fP ()"
.br
.ti -1c
.RI "void \fBDrawField\fP ()"
.br
.ti -1c
.RI "bool \fBIsFinish\fP ()"
.br
.in -1c
.SH "Методы"
.PP 
.SS "void Memory_Trainer\&.IGameInterface\&.DrawField ()"

.SS "bool Memory_Trainer\&.IGameInterface\&.IsFinish ()"

.SS "void Memory_Trainer\&.IGameInterface\&.OpenGame ()"

.SS "void Memory_Trainer\&.IGameInterface\&.SaveGame ()"

.SS "void Memory_Trainer\&.IGameInterface\&.ShowInfo ()"

.SS "void Memory_Trainer\&.IGameInterface\&.ShowRules ()"


.SH "Автор"
.PP 
Автоматически создано Doxygen для Тренажер памяти из исходного текста\&.
