.TH "Memory_Trainer::Properties::Resources" 3 "Вс 8 Дек 2019" "Тренажер памяти" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Memory_Trainer::Properties::Resources \- Класс ресурса со строгой типизацией для поиска локализованных строк и т\&.д\&.  

.SH SYNOPSIS
.br
.PP
.SS "Закрытые члены"

.in +1c
.ti -1c
.RI "internal \fBResources\fP ()"
.br
.in -1c
.SS "Закрытые статические данные"

.in +1c
.ti -1c
.RI "static private global::System \fBResources\fP ResourceManager \fBresourceMan\fP"
.br
.ti -1c
.RI "static private global::System Globalization CultureInfo \fBresourceCulture\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
Класс ресурса со строгой типизацией для поиска локализованных строк и т\&.д\&. 


.PP
См\&. определение в файле Resources\&.Designer\&.cs строка 25
.SH "Конструктор(ы)"
.PP 
.SS "internal Memory_Trainer::Properties::Resources::Resources ()\fC [private]\fP"

.PP
См\&. определение в файле Resources\&.Designer\&.cs строка 32
.SH "Данные класса"
.PP 
.SS "private global::System Globalization CultureInfo Memory_Trainer::Properties::Resources::resourceCulture\fC [static]\fP, \fC [private]\fP"

.PP
См\&. определение в файле Resources\&.Designer\&.cs строка 29
.SS "private global::System \fBResources\fP ResourceManager Memory_Trainer::Properties::Resources::resourceMan\fC [static]\fP, \fC [private]\fP"

.PP
См\&. определение в файле Resources\&.Designer\&.cs строка 27

.SH "Автор"
.PP 
Автоматически создано Doxygen для Тренажер памяти из исходного текста\&.
