.TH "Memory_Trainer" 3 "Вс 8 Дек 2019" "Тренажер памяти" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Memory_Trainer
.SH SYNOPSIS
.br
.PP
.SS "Пространства имен"

.in +1c
.ti -1c
.RI " \fBProperties\fP"
.br
.in -1c
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBFormAboutThimbles\fP"
.br
.ti -1c
.RI "class \fBFormMemoryTrainer\fP"
.br
.ti -1c
.RI "class \fBFormShowRulesThimbles\fP"
.br
.ti -1c
.RI "class \fBFormThimbles\fP"
.br
.RI "Класс для формы с игрой "
.ti -1c
.RI "interface \fBIGameInterface\fP"
.br
.ti -1c
.RI "class \fBProgram\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Тренажер памяти из исходного текста\&.
