.TH "Memory_Trainer.FormThimbles" 3 "Вс 8 Дек 2019" "Тренажер памяти" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Memory_Trainer.FormThimbles \- Класс для формы с игрой  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:Form и \fBMemory_Trainer\&.IGameInterface\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBFormThimbles\fP ()"
.br
.RI "Конструктор \fBFormThimbles\fP "
.ti -1c
.RI "void \fBDrawField\fP ()"
.br
.RI "Функция прорисовывает игровое поле\&. "
.ti -1c
.RI "void \fBSaveGame\fP ()"
.br
.RI "Функция для сохранения игры "
.ti -1c
.RI "void \fBOpenGame\fP ()"
.br
.RI "Функция для открытия сохраненной игры "
.ti -1c
.RI "void \fBShowRules\fP ()"
.br
.RI "Функция для отображения правил "
.ti -1c
.RI "void \fBShowInfo\fP ()"
.br
.RI "Функция для отображения информации об игре "
.ti -1c
.RI "bool \fBIsFinish\fP ()"
.br
.RI "Проверка на победу, на окончание игры "
.in -1c
.SS "Закрытые члены"

.in +1c
.ti -1c
.RI "void \fBFormThimbles_Load\fP (object sender, EventArgs e)"
.br
.RI "Функция инициализации формы "
.ti -1c
.RI "void \fBButtonAbout_Click\fP (object sender, EventArgs e)"
.br
.RI "Обработка нажатия на кнопку 'О программе' "
.ti -1c
.RI "void \fBButtonStartGame_Click\fP (object sender, EventArgs e)"
.br
.RI "Обработка события нажатия на клавишу начала игры\&. "
.ti -1c
.RI "void \fBAnimate\fP ()"
.br
.RI "Функция для анимации "
.ti -1c
.RI "void \fBShuffle\fP ()"
.br
.RI "Функция для перемешивания наперстков "
.ti -1c
.RI "void \fBTimerOneToTop_Tick\fP (object sender, EventArgs e)"
.br
.RI "Таймер для анимации подъема одного наперстка вверх "
.ti -1c
.RI "void \fBTimerShuffle_Tick\fP (object sender, EventArgs e)"
.br
.RI "Таймер для анимации перемешивания напестков "
.ti -1c
.RI "void \fBTimerCheckWin_Tick\fP (object sender, EventArgs e)"
.br
.RI "Таймер проверки на победу "
.ti -1c
.RI "void \fBFormThimbles_Click\fP (object sender, EventArgs e)"
.br
.RI "Обработка события нажатия на форму "
.ti -1c
.RI "void \fBButtonSave_Click\fP (object sender, EventArgs e)"
.br
.RI "Функция для обработки события клика по кнопке 'Сохранить' "
.ti -1c
.RI "void \fBButtonOpen_Click\fP (object sender, EventArgs e)"
.br
.RI "Обработчик события клика по кнопке 'Открыть' "
.ti -1c
.RI "void \fBButtonRules_Click\fP (object sender, EventArgs e)"
.br
.RI "Обработчик события клика по кнопке 'Правила' "
.ti -1c
.RI "protected override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.ti -1c
.RI "private void \fBInitializeComponent\fP ()"
.br
.RI "Required method for Designer support - do not modify the contents of this method with the code editor\&. "
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "int \fBind1\fP"
.br
.RI "Индекс 1 обмениваемого наперстка "
.ti -1c
.RI "int \fBind2\fP"
.br
.RI "Индекс 2 обмениваемого наперстка "
.ti -1c
.RI "int \fBx1\fP"
.br
.RI "Позиция обмена 1 по х\&. "
.ti -1c
.RI "int \fBx2\fP"
.br
.RI "Позиция обмена 2 по х\&. "
.ti -1c
.RI "int \fBy1\fP"
.br
.RI "Позиция обмена 1 по y\&. "
.ti -1c
.RI "int \fBy2\fP"
.br
.RI "Позиция обмена 2 по y\&. "
.ti -1c
.RI "int \fBdx\fP"
.br
.RI "Смещение по х\&. "
.ti -1c
.RI "int \fBdy\fP"
.br
.RI "Смещение по у\&. "
.ti -1c
.RI "int \fBcurstep\fP"
.br
.RI "Текущий шаг анимации\&. "
.ti -1c
.RI "int \fBlevel\fP"
.br
.RI "Уровень "
.ti -1c
.RI "int \fBbPos\fP"
.br
.RI "Позиция мяча "
.ti -1c
.RI "int \fBchoise\fP"
.br
.RI "Выбор наперстка "
.ti -1c
.RI "int \fBv\fP"
.br
.RI "Скорость анимации "
.ti -1c
.RI "int \fBkey\fP"
.br
.RI "Ключ шифрования "
.ti -1c
.RI "double \fBthimble1_pos_x\fP"
.br
.RI "Позиция наперстка 1 по х\&. "
.ti -1c
.RI "double \fBthimble1_pos_y\fP"
.br
.RI "Позиция наперстка 1 по у\&. "
.ti -1c
.RI "double \fBthimble2_pos_x\fP"
.br
.RI "Позиция наперстка 2 по х\&. "
.ti -1c
.RI "double \fBthimble2_pos_y\fP"
.br
.RI "Позиция наперстка 2 по у\&. "
.ti -1c
.RI "bool \fBisAnimation\fP"
.br
.RI "Флаг анимации\&. "
.ti -1c
.RI "bool \fBisToTop\fP"
.br
.RI "Флаг - поднимаем ли? "
.ti -1c
.RI "Rectangle[] \fBthimbles\fP"
.br
.RI "Массив прямоугольников для отображения наперстков "
.ti -1c
.RI "Rectangle \fBball_rect\fP"
.br
.RI "Прямоугольник для отображения мяча\&. "
.ti -1c
.RI "Bitmap \fBthimble_image\fP"
.br
.RI "Изображение для наперстка "
.ti -1c
.RI "Bitmap \fBball_image\fP"
.br
.RI "Изображение для мяча\&. "
.ti -1c
.RI "Graphics \fBg\fP"
.br
.RI "Объект для отображения графика\&. "
.ti -1c
.RI "Random \fBrand\fP"
.br
.RI "Объект для рандома\&. "
.ti -1c
.RI "private System ComponentModel IContainer \fBcomponents\fP = null"
.br
.RI "Required designer variable\&. "
.ti -1c
.RI "private System Windows Forms Button \fBbuttonStartGame\fP"
.br
.ti -1c
.RI "private System Windows Forms Timer \fBtimerShuffle\fP"
.br
.ti -1c
.RI "private System Windows Forms Timer \fBtimerOneToTop\fP"
.br
.ti -1c
.RI "private System Windows Forms Timer \fBtimerAllToTop\fP"
.br
.ti -1c
.RI "private System Windows Forms PictureBox \fBpbBackground\fP"
.br
.ti -1c
.RI "private System Windows Forms Label \fBlabel\fP"
.br
.ti -1c
.RI "private System Windows Forms Button \fBbuttonSave\fP"
.br
.ti -1c
.RI "private System Windows Forms Button \fBbuttonOpen\fP"
.br
.ti -1c
.RI "private System Windows Forms Button \fBbuttonRules\fP"
.br
.ti -1c
.RI "private System Windows Forms Button \fBbuttonAbout\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
Класс для формы с игрой 


.PP
См\&. определение в файле FormThimbles\&.cs строка 10
.SH "Конструктор(ы)"
.PP 
.SS "Memory_Trainer\&.FormThimbles\&.FormThimbles ()"

.PP
Конструктор \fBFormThimbles\fP 
.PP
См\&. определение в файле FormThimbles\&.cs строка 157
.SH "Методы"
.PP 
.SS "void Memory_Trainer\&.FormThimbles\&.Animate ()\fC [private]\fP"

.PP
Функция для анимации 
.PP
См\&. определение в файле FormThimbles\&.cs строка 206
.SS "void Memory_Trainer\&.FormThimbles\&.ButtonAbout_Click (object sender, EventArgs e)\fC [private]\fP"

.PP
Обработка нажатия на кнопку 'О программе' 
.PP
\fBАргументы\fP
.RS 4
\fIsender\fP Объект, который в обработке
.br
\fIe\fP Аргументы события
.RE
.PP

.PP
См\&. определение в файле FormThimbles\&.cs строка 148
.SS "void Memory_Trainer\&.FormThimbles\&.ButtonOpen_Click (object sender, EventArgs e)\fC [private]\fP"

.PP
Обработчик события клика по кнопке 'Открыть' 
.PP
\fBАргументы\fP
.RS 4
\fIsender\fP Объект, который в обработке
.br
\fIe\fP Аргументы события
.RE
.PP

.PP
См\&. определение в файле FormThimbles\&.cs строка 550
.SS "void Memory_Trainer\&.FormThimbles\&.ButtonRules_Click (object sender, EventArgs e)\fC [private]\fP"

.PP
Обработчик события клика по кнопке 'Правила' 
.PP
\fBАргументы\fP
.RS 4
\fIsender\fP Объект, который в обработке
.br
\fIe\fP Аргументы события
.RE
.PP

.PP
См\&. определение в файле FormThimbles\&.cs строка 564
.SS "void Memory_Trainer\&.FormThimbles\&.ButtonSave_Click (object sender, EventArgs e)\fC [private]\fP"

.PP
Функция для обработки события клика по кнопке 'Сохранить' 
.PP
\fBАргументы\fP
.RS 4
\fIsender\fP Объект, который в обработке
.br
\fIe\fP Аргументы события
.RE
.PP

.PP
См\&. определение в файле FormThimbles\&.cs строка 539
.SS "void Memory_Trainer\&.FormThimbles\&.ButtonStartGame_Click (object sender, EventArgs e)\fC [private]\fP"

.PP
Обработка события нажатия на клавишу начала игры\&. 
.PP
\fBАргументы\fP
.RS 4
\fIsender\fP Объект, который в обработке
.br
\fIe\fP Аргументы события
.RE
.PP

.PP
См\&. определение в файле FormThimbles\&.cs строка 192
.SS "protected override void Memory_Trainer\&.FormThimbles\&.Dispose (bool disposing)\fC [private]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBАргументы\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.PP
См\&. определение в файле FormThimbles\&.Designer\&.cs строка 14
.SS "void Memory_Trainer\&.FormThimbles\&.DrawField ()"

.PP
Функция прорисовывает игровое поле\&. 
.PP
Замещает \fBMemory_Trainer\&.IGameInterface\fP\&.
.PP
См\&. определение в файле FormThimbles\&.cs строка 171
.SS "void Memory_Trainer\&.FormThimbles\&.FormThimbles_Click (object sender, EventArgs e)\fC [private]\fP"

.PP
Обработка события нажатия на форму 
.PP
\fBАргументы\fP
.RS 4
\fIsender\fP Объект, который в обработке
.br
\fIe\fP Аргументы события
.RE
.PP

.PP
См\&. определение в файле FormThimbles\&.cs строка 386
.SS "void Memory_Trainer\&.FormThimbles\&.FormThimbles_Load (object sender, EventArgs e)\fC [private]\fP"

.PP
Функция инициализации формы 
.PP
\fBАргументы\fP
.RS 4
\fIsender\fP Объект, который в обработке
.br
\fIe\fP Аргументы события
.RE
.PP

.PP
См\&. определение в файле FormThimbles\&.cs строка 121
.SS "private void Memory_Trainer\&.FormThimbles\&.InitializeComponent ()\fC [private]\fP"

.PP
Required method for Designer support - do not modify the contents of this method with the code editor\&. 
.PP
См\&. определение в файле FormThimbles\&.Designer\&.cs строка 26
.SS "bool Memory_Trainer\&.FormThimbles\&.IsFinish ()"

.PP
Проверка на победу, на окончание игры 
.PP
\fBВозвращает\fP
.RS 4
true - в случае финиша, false - в случае продолжения игры
.RE
.PP

.PP
Замещает \fBMemory_Trainer\&.IGameInterface\fP\&.
.PP
См\&. определение в файле FormThimbles\&.cs строка 498
.SS "void Memory_Trainer\&.FormThimbles\&.OpenGame ()"

.PP
Функция для открытия сохраненной игры 
.PP
Замещает \fBMemory_Trainer\&.IGameInterface\fP\&.
.PP
См\&. определение в файле FormThimbles\&.cs строка 442
.SS "void Memory_Trainer\&.FormThimbles\&.SaveGame ()"

.PP
Функция для сохранения игры 
.PP
Замещает \fBMemory_Trainer\&.IGameInterface\fP\&.
.PP
См\&. определение в файле FormThimbles\&.cs строка 428
.SS "void Memory_Trainer\&.FormThimbles\&.ShowInfo ()"

.PP
Функция для отображения информации об игре 
.PP
Замещает \fBMemory_Trainer\&.IGameInterface\fP\&.
.PP
См\&. определение в файле FormThimbles\&.cs строка 483
.SS "void Memory_Trainer\&.FormThimbles\&.ShowRules ()"

.PP
Функция для отображения правил 
.PP
Замещает \fBMemory_Trainer\&.IGameInterface\fP\&.
.PP
См\&. определение в файле FormThimbles\&.cs строка 469
.SS "void Memory_Trainer\&.FormThimbles\&.Shuffle ()\fC [private]\fP"

.PP
Функция для перемешивания наперстков 
.PP
См\&. определение в файле FormThimbles\&.cs строка 226
.SS "void Memory_Trainer\&.FormThimbles\&.TimerCheckWin_Tick (object sender, EventArgs e)\fC [private]\fP"

.PP
Таймер проверки на победу 
.PP
\fBАргументы\fP
.RS 4
\fIsender\fP Объект, который в обработке
.br
\fIe\fP Аргументы события
.RE
.PP

.PP
См\&. определение в файле FormThimbles\&.cs строка 352
.SS "void Memory_Trainer\&.FormThimbles\&.TimerOneToTop_Tick (object sender, EventArgs e)\fC [private]\fP"

.PP
Таймер для анимации подъема одного наперстка вверх 
.PP
\fBАргументы\fP
.RS 4
\fIsender\fP Объект, который в обработке
.br
\fIe\fP Аргументы события
.RE
.PP

.PP
См\&. определение в файле FormThimbles\&.cs строка 259
.SS "void Memory_Trainer\&.FormThimbles\&.TimerShuffle_Tick (object sender, EventArgs e)\fC [private]\fP"

.PP
Таймер для анимации перемешивания напестков 
.PP
\fBАргументы\fP
.RS 4
\fIsender\fP Объект, который в обработке
.br
\fIe\fP Аргументы события
.RE
.PP

.PP
См\&. определение в файле FormThimbles\&.cs строка 294
.SH "Данные класса"
.PP 
.SS "Bitmap Memory_Trainer\&.FormThimbles\&.ball_image\fC [private]\fP"

.PP
Изображение для мяча\&. 
.PP
См\&. определение в файле FormThimbles\&.cs строка 106
.SS "Rectangle Memory_Trainer\&.FormThimbles\&.ball_rect\fC [private]\fP"

.PP
Прямоугольник для отображения мяча\&. 
.PP
См\&. определение в файле FormThimbles\&.cs строка 98
.SS "int Memory_Trainer\&.FormThimbles\&.bPos\fC [private]\fP"

.PP
Позиция мяча 
.PP
См\&. определение в файле FormThimbles\&.cs строка 54
.SS "private System Windows Forms Button Memory_Trainer\&.FormThimbles\&.buttonAbout\fC [private]\fP"

.PP
См\&. определение в файле FormThimbles\&.Designer\&.cs строка 184
.SS "private System Windows Forms Button Memory_Trainer\&.FormThimbles\&.buttonOpen\fC [private]\fP"

.PP
См\&. определение в файле FormThimbles\&.Designer\&.cs строка 182
.SS "private System Windows Forms Button Memory_Trainer\&.FormThimbles\&.buttonRules\fC [private]\fP"

.PP
См\&. определение в файле FormThimbles\&.Designer\&.cs строка 183
.SS "private System Windows Forms Button Memory_Trainer\&.FormThimbles\&.buttonSave\fC [private]\fP"

.PP
См\&. определение в файле FormThimbles\&.Designer\&.cs строка 181
.SS "private System Windows Forms Button Memory_Trainer\&.FormThimbles\&.buttonStartGame\fC [private]\fP"

.PP
См\&. определение в файле FormThimbles\&.Designer\&.cs строка 175
.SS "int Memory_Trainer\&.FormThimbles\&.choise\fC [private]\fP"

.PP
Выбор наперстка 
.PP
См\&. определение в файле FormThimbles\&.cs строка 58
.SS "private System ComponentModel IContainer Memory_Trainer\&.FormThimbles\&.components = null\fC [private]\fP"

.PP
Required designer variable\&. 
.PP
См\&. определение в файле FormThimbles\&.Designer\&.cs строка 8
.SS "int Memory_Trainer\&.FormThimbles\&.curstep\fC [private]\fP"

.PP
Текущий шаг анимации\&. 
.PP
См\&. определение в файле FormThimbles\&.cs строка 46
.SS "int Memory_Trainer\&.FormThimbles\&.dx\fC [private]\fP"

.PP
Смещение по х\&. 
.PP
См\&. определение в файле FormThimbles\&.cs строка 38
.SS "int Memory_Trainer\&.FormThimbles\&.dy\fC [private]\fP"

.PP
Смещение по у\&. 
.PP
См\&. определение в файле FormThimbles\&.cs строка 42
.SS "Graphics Memory_Trainer\&.FormThimbles\&.g\fC [private]\fP"

.PP
Объект для отображения графика\&. 
.PP
См\&. определение в файле FormThimbles\&.cs строка 110
.SS "int Memory_Trainer\&.FormThimbles\&.ind1\fC [private]\fP"

.PP
Индекс 1 обмениваемого наперстка 
.PP
См\&. определение в файле FormThimbles\&.cs строка 14
.SS "int Memory_Trainer\&.FormThimbles\&.ind2\fC [private]\fP"

.PP
Индекс 2 обмениваемого наперстка 
.PP
См\&. определение в файле FormThimbles\&.cs строка 18
.SS "bool Memory_Trainer\&.FormThimbles\&.isAnimation\fC [private]\fP"

.PP
Флаг анимации\&. 
.PP
См\&. определение в файле FormThimbles\&.cs строка 86
.SS "bool Memory_Trainer\&.FormThimbles\&.isToTop\fC [private]\fP"

.PP
Флаг - поднимаем ли? 
.PP
См\&. определение в файле FormThimbles\&.cs строка 90
.SS "int Memory_Trainer\&.FormThimbles\&.key\fC [private]\fP"

.PP
Ключ шифрования 
.PP
См\&. определение в файле FormThimbles\&.cs строка 66
.SS "private System Windows Forms Label Memory_Trainer\&.FormThimbles\&.label\fC [private]\fP"

.PP
См\&. определение в файле FormThimbles\&.Designer\&.cs строка 180
.SS "int Memory_Trainer\&.FormThimbles\&.level\fC [private]\fP"

.PP
Уровень 
.PP
См\&. определение в файле FormThimbles\&.cs строка 50
.SS "private System Windows Forms PictureBox Memory_Trainer\&.FormThimbles\&.pbBackground\fC [private]\fP"

.PP
См\&. определение в файле FormThimbles\&.Designer\&.cs строка 179
.SS "Random Memory_Trainer\&.FormThimbles\&.rand\fC [private]\fP"

.PP
Объект для рандома\&. 
.PP
См\&. определение в файле FormThimbles\&.cs строка 114
.SS "double Memory_Trainer\&.FormThimbles\&.thimble1_pos_x\fC [private]\fP"

.PP
Позиция наперстка 1 по х\&. 
.PP
См\&. определение в файле FormThimbles\&.cs строка 70
.SS "double Memory_Trainer\&.FormThimbles\&.thimble1_pos_y\fC [private]\fP"

.PP
Позиция наперстка 1 по у\&. 
.PP
См\&. определение в файле FormThimbles\&.cs строка 74
.SS "double Memory_Trainer\&.FormThimbles\&.thimble2_pos_x\fC [private]\fP"

.PP
Позиция наперстка 2 по х\&. 
.PP
См\&. определение в файле FormThimbles\&.cs строка 78
.SS "double Memory_Trainer\&.FormThimbles\&.thimble2_pos_y\fC [private]\fP"

.PP
Позиция наперстка 2 по у\&. 
.PP
См\&. определение в файле FormThimbles\&.cs строка 82
.SS "Bitmap Memory_Trainer\&.FormThimbles\&.thimble_image\fC [private]\fP"

.PP
Изображение для наперстка 
.PP
См\&. определение в файле FormThimbles\&.cs строка 102
.SS "Rectangle [] Memory_Trainer\&.FormThimbles\&.thimbles\fC [private]\fP"

.PP
Массив прямоугольников для отображения наперстков 
.PP
См\&. определение в файле FormThimbles\&.cs строка 94
.SS "private System Windows Forms Timer Memory_Trainer\&.FormThimbles\&.timerAllToTop\fC [private]\fP"

.PP
См\&. определение в файле FormThimbles\&.Designer\&.cs строка 178
.SS "private System Windows Forms Timer Memory_Trainer\&.FormThimbles\&.timerOneToTop\fC [private]\fP"

.PP
См\&. определение в файле FormThimbles\&.Designer\&.cs строка 177
.SS "private System Windows Forms Timer Memory_Trainer\&.FormThimbles\&.timerShuffle\fC [private]\fP"

.PP
См\&. определение в файле FormThimbles\&.Designer\&.cs строка 176
.SS "int Memory_Trainer\&.FormThimbles\&.v\fC [private]\fP"

.PP
Скорость анимации 
.PP
См\&. определение в файле FormThimbles\&.cs строка 62
.SS "int Memory_Trainer\&.FormThimbles\&.x1\fC [private]\fP"

.PP
Позиция обмена 1 по х\&. 
.PP
См\&. определение в файле FormThimbles\&.cs строка 22
.SS "int Memory_Trainer\&.FormThimbles\&.x2\fC [private]\fP"

.PP
Позиция обмена 2 по х\&. 
.PP
См\&. определение в файле FormThimbles\&.cs строка 26
.SS "int Memory_Trainer\&.FormThimbles\&.y1\fC [private]\fP"

.PP
Позиция обмена 1 по y\&. 
.PP
См\&. определение в файле FormThimbles\&.cs строка 30
.SS "int Memory_Trainer\&.FormThimbles\&.y2\fC [private]\fP"

.PP
Позиция обмена 2 по y\&. 
.PP
См\&. определение в файле FormThimbles\&.cs строка 34

.SH "Автор"
.PP 
Автоматически создано Doxygen для Тренажер памяти из исходного текста\&.
