.TH "Memory_Trainer.Program" 3 "Вс 8 Дек 2019" "Тренажер памяти" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Memory_Trainer.Program
.SH SYNOPSIS
.br
.PP
.SS "Закрытые статические члены"

.in +1c
.ti -1c
.RI "static void \fBMain\fP ()"
.br
.RI "Главная точка входа для приложения\&. "
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле Program\&.cs строка 6
.SH "Методы"
.PP 
.SS "static void Memory_Trainer\&.Program\&.Main ()\fC [static]\fP, \fC [private]\fP"

.PP
Главная точка входа для приложения\&. 
.PP
См\&. определение в файле Program\&.cs строка 13

.SH "Автор"
.PP 
Автоматически создано Doxygen для Тренажер памяти из исходного текста\&.
