.TH "Memory_Trainer::Properties::Settings" 3 "Вс 8 Дек 2019" "Тренажер памяти" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Memory_Trainer::Properties::Settings
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:ApplicationSettingsBase\&.
.SS "Закрытые статические данные"

.in +1c
.ti -1c
.RI "static private \fBSettings\fP \fBdefaultInstance\fP = ((\fBSettings\fP)(global::System\&.Configuration\&.ApplicationSettingsBase\&.Synchronized(new \fBSettings\fP())))"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле Settings\&.Designer\&.cs строка 17
.SH "Данные класса"
.PP 
.SS "private \fBSettings\fP Memory_Trainer::Properties::Settings::defaultInstance = ((\fBSettings\fP)(global::System\&.Configuration\&.ApplicationSettingsBase\&.Synchronized(new \fBSettings\fP())))\fC [static]\fP, \fC [private]\fP"

.PP
См\&. определение в файле Settings\&.Designer\&.cs строка 20

.SH "Автор"
.PP 
Автоматически создано Doxygen для Тренажер памяти из исходного текста\&.
