.TH "Memory_Trainer::Properties" 3 "Вс 8 Дек 2019" "Тренажер памяти" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Memory_Trainer::Properties
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBResources\fP"
.br
.RI "Класс ресурса со строгой типизацией для поиска локализованных строк и т\&.д\&. "
.ti -1c
.RI "class \fBSettings\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Тренажер памяти из исходного текста\&.
