.TH "Memory_Trainer.FormMemoryTrainer" 3 "Вс 8 Дек 2019" "Тренажер памяти" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Memory_Trainer.FormMemoryTrainer
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:Form\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBFormMemoryTrainer\fP ()"
.br
.in -1c
.SS "Закрытые члены"

.in +1c
.ti -1c
.RI "void \fBbuttonFindAPair_Click\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBbuttonLostWord_Click\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBbuttonQuadShulte_Click\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBbuttonMemoryMatrix_Click\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBbuttonThimbles_Click\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "protected override void \fBDispose\fP (bool disposing)"
.br
.RI "Освободить все используемые ресурсы\&. "
.ti -1c
.RI "private void \fBInitializeComponent\fP ()"
.br
.RI "Обязательный метод для поддержки конструктора - не изменяйте содержимое данного метода при помощи редактора кода\&. "
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "private System ComponentModel IContainer \fBcomponents\fP = null"
.br
.RI "Требуется переменная конструктора\&. "
.ti -1c
.RI "private System Windows Forms Button \fBbuttonFindAPair\fP"
.br
.ti -1c
.RI "private System Windows Forms Button \fBbuttonQuadShulte\fP"
.br
.ti -1c
.RI "private System Windows Forms Button \fBbuttonLostWord\fP"
.br
.ti -1c
.RI "private System Windows Forms Button \fBbuttonMemoryMatrix\fP"
.br
.ti -1c
.RI "private System Windows Forms Button \fBbuttonThimbles\fP"
.br
.ti -1c
.RI "private System Windows Forms PictureBox \fBpictureBox1\fP"
.br
.in -1c
.SH "Конструктор(ы)"
.PP 
.SS "Memory_Trainer\&.FormMemoryTrainer\&.FormMemoryTrainer ()"

.SH "Методы"
.PP 
.SS "void Memory_Trainer\&.FormMemoryTrainer\&.buttonFindAPair_Click (object sender, EventArgs e)\fC [private]\fP"

.SS "void Memory_Trainer\&.FormMemoryTrainer\&.buttonLostWord_Click (object sender, EventArgs e)\fC [private]\fP"

.SS "void Memory_Trainer\&.FormMemoryTrainer\&.buttonMemoryMatrix_Click (object sender, EventArgs e)\fC [private]\fP"

.SS "void Memory_Trainer\&.FormMemoryTrainer\&.buttonQuadShulte_Click (object sender, EventArgs e)\fC [private]\fP"

.SS "void Memory_Trainer\&.FormMemoryTrainer\&.buttonThimbles_Click (object sender, EventArgs e)\fC [private]\fP"

.SS "protected override void Memory_Trainer\&.FormMemoryTrainer\&.Dispose (bool disposing)\fC [private]\fP"

.PP
Освободить все используемые ресурсы\&. 
.PP
\fBАргументы\fP
.RS 4
\fIdisposing\fP истинно, если управляемый ресурс должен быть удален; иначе ложно\&.
.RE
.PP

.SS "private void Memory_Trainer\&.FormMemoryTrainer\&.InitializeComponent ()\fC [private]\fP"

.PP
Обязательный метод для поддержки конструктора - не изменяйте содержимое данного метода при помощи редактора кода\&. 
.SH "Данные класса"
.PP 
.SS "private System Windows Forms Button Memory_Trainer\&.FormMemoryTrainer\&.buttonFindAPair\fC [private]\fP"

.SS "private System Windows Forms Button Memory_Trainer\&.FormMemoryTrainer\&.buttonLostWord\fC [private]\fP"

.SS "private System Windows Forms Button Memory_Trainer\&.FormMemoryTrainer\&.buttonMemoryMatrix\fC [private]\fP"

.SS "private System Windows Forms Button Memory_Trainer\&.FormMemoryTrainer\&.buttonQuadShulte\fC [private]\fP"

.SS "private System Windows Forms Button Memory_Trainer\&.FormMemoryTrainer\&.buttonThimbles\fC [private]\fP"

.SS "private System ComponentModel IContainer Memory_Trainer\&.FormMemoryTrainer\&.components = null\fC [private]\fP"

.PP
Требуется переменная конструктора\&. 
.SS "private System Windows Forms PictureBox Memory_Trainer\&.FormMemoryTrainer\&.pictureBox1\fC [private]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для Тренажер памяти из исходного текста\&.
