.TH "C:/Users/yana/Desktop/tmp/Essakov/memory_trainer_game/MemoryTrainer/Memory Trainer/obj/Debug/TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs" 3 "Вс 8 Дек 2019" "Тренажер памяти" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/yana/Desktop/tmp/Essakov/memory_trainer_game/MemoryTrainer/Memory Trainer/obj/Debug/TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs
.SH SYNOPSIS
.br
.PP
.SH "Автор"
.PP 
Автоматически создано Doxygen для Тренажер памяти из исходного текста\&.
