.TH "C:/Users/yana/Desktop/tmp/Essakov/memory_trainer_game/MemoryTrainer/Memory Trainer/obj/Debug/TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs" 3 "Вс 8 Дек 2019" "Тренажер памяти" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/yana/Desktop/tmp/Essakov/memory_trainer_game/MemoryTrainer/Memory Trainer/obj/Debug/TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs
.SH SYNOPSIS
.br
.PP
.SH "Автор"
.PP 
Автоматически создано Doxygen для Тренажер памяти из исходного текста\&.
